/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './auth.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
class AuthModuleInjector extends import0.ɵNgModuleInjector<import1.AuthModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _ReactiveFormsModule_2:import3.ReactiveFormsModule;
  _AuthModule_3:import1.AuthModule;
  __NgLocalization_4:import2.NgLocaleLocalization;
  __FormBuilder_5:import3.FormBuilder;
  __ɵi_6:import3.ɵi;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_4():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == null)) { (this.__NgLocalization_4 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_4;
  }
  get _FormBuilder_5():import3.FormBuilder {
    if ((this.__FormBuilder_5 == null)) { (this.__FormBuilder_5 = new import3.FormBuilder()); }
    return this.__FormBuilder_5;
  }
  get _ɵi_6():import3.ɵi {
    if ((this.__ɵi_6 == null)) { (this.__ɵi_6 = new import3.ɵi()); }
    return this.__ɵi_6;
  }
  createInternal():import1.AuthModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._ReactiveFormsModule_2 = new import3.ReactiveFormsModule();
    this._AuthModule_3 = new import1.AuthModule();
    return this._AuthModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_2; }
    if ((token === import1.AuthModule)) { return this._AuthModule_3; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import3.FormBuilder)) { return this._FormBuilder_5; }
    if ((token === import3.ɵi)) { return this._ɵi_6; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AuthModuleNgFactory:import0.NgModuleFactory<import1.AuthModule> = new import0.NgModuleFactory<any>(AuthModuleInjector,import1.AuthModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdi5sZWR5YWV2L0RvY3VtZW50cy9Qcm9qZWN0cy9DZWxsdWxhckF1dG9tYXRvbi1NRUFOLS9hc3NldHMvYXBwL2F1dGgvYXV0aC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvdi5sZWR5YWV2L0RvY3VtZW50cy9Qcm9qZWN0cy9DZWxsdWxhckF1dG9tYXRvbi1NRUFOLS9hc3NldHMvYXBwL2F1dGgvYXV0aC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
