/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './logout.component';
import * as import2 from './auth.service';
import * as import3 from '@angular/router';
const styles_LogoutComponent:any[] = ([] as any[]);
export const RenderType_LogoutComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_LogoutComponent,
  data: {}
}
);
export function View_LogoutComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n        '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'col-md-8 col-md-offset-2'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n            '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'button',[[
        'class',
        'btn btn-danger'
      ]
      ],(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.LogoutComponent = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.onLogout()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Logout'])),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(null as any),(null as any));
}
function View_LogoutComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-logout',([] as any[]),(null as any),(null as any),(null as any),View_LogoutComponent_0,RenderType_LogoutComponent)),
    import0.ɵdid(24576,(null as any),0,import1.LogoutComponent,[
      import2.AuthService,
      import3.Router
    ]
    ,(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const LogoutComponentNgFactory:import0.ComponentFactory<import1.LogoutComponent> = import0.ɵccf('app-logout',import1.LogoutComponent,View_LogoutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdi5sZWR5YWV2L0RvY3VtZW50cy9Qcm9qZWN0cy9DZWxsdWxhckF1dG9tYXRvbi1NRUFOLS9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy92LmxlZHlhZXYvRG9jdW1lbnRzL1Byb2plY3RzL0NlbGx1bGFyQXV0b21hdG9uLU1FQU4tL2Fzc2V0cy9hcHAvYXV0aC9sb2dvdXQuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvdi5sZWR5YWV2L0RvY3VtZW50cy9Qcm9qZWN0cy9DZWxsdWxhckF1dG9tYXRvbi1NRUFOLS9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cy5Mb2dvdXRDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1VzZXJzL3YubGVkeWFldi9Eb2N1bWVudHMvUHJvamVjdHMvQ2VsbHVsYXJBdXRvbWF0b24tTUVBTi0vYXNzZXRzL2FwcC9hdXRoL2xvZ291dC5jb21wb25lbnQudHMuTG9nb3V0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtbWQtOCBjb2wtbWQtb2Zmc2V0LTJcIj5cbiAgICAgICAgICAgIDxidXR0b24gY2xhc3M9XCJidG4gYnRuLWRhbmdlclwiIChjbGljayk9XCJvbkxvZ291dCgpXCI+TG9nb3V0PC9idXR0b24+XG4gICAgICAgIDwvZGl2PlxuICAgICIsIjxhcHAtbG9nb3V0PjwvYXBwLWxvZ291dD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUNRO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBc0M7TUFDbEM7UUFBQTtRQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7TUFBQTtNQUErQjtRQUFBO1FBQUE7TUFBQTtNQUEvQjtJQUFBO0lBQW9EO0lBQWU7SUFDakU7Ozs7OztJQ0hkO2dCQUFBOzs7SUFBQTtLQUFBOzs7OyJ9
